env:
  es2021: true
extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: latest
  sourceType: module
plugins:
  - promise
  - react
  - prettier
  - "@typescript-eslint"
  - "react-hooks"
rules:
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/no-explicit-any": 0 # would like to change this in the future
  "@typescript-eslint/no-unused-vars":
    - error
    - ignoreRestSiblings: true
      argsIgnorePattern: "^_"
  "promise/prefer-await-to-then": error
  "@typescript-eslint/no-non-null-assertion": error
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/await-thenable": 2
  "@typescript-eslint/no-floating-promises": 0 # would like to change to error
  "@typescript-eslint/no-for-in-array": 2
  "@typescript-eslint/no-unnecessary-type-assertion": 2
  "@typescript-eslint/no-unsafe-argument": 0 # would like to add, this mostly are included in typechecking recommended
  "@typescript-eslint/no-unsafe-assignment": 0 # would like to add
  "@typescript-eslint/no-unsafe-call": 0 # would like to add
  "@typescript-eslint/restrict-plus-operands": 2
  "@typescript-eslint/restrict-template-expressions": 0 # no need to add
  "@typescript-eslint/unbound-method": 2
  "curly": [error, "all"]
  "prettier/prettier": 1

